# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -o built
        
    - name: Upload Go built
      uses: actions/upload-artifact@v3
      with:
        name: built-artifact
        path: built
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: "{%- raw -%} ${{ secrets.SSH_PRIVATE_KEY }}"
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    
    - name: Adding Known Hosts
      run: ssh-keyscan -H 152.70.184.41 >> ~/.ssh/known_hosts
    
    - name: Deploy with rsync
      run: rsync -avz ./built ubuntu@152.70.184.41:/home/ubuntu/diplomawork_backend/src/built
  
